import { createClient } from "@/utils/supabase/server";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const supabase = await createClient();

	const user = await supabase.auth.getUser();

	const profile = await supabase
		.from("profiles")
		.select()
		.eq("id", user.data.user?.id);

  console.log(profile.data)

	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
